export default {
    modes: ["net", "ai", "server", "hotseat"],
    mode: "net",
    connections: ["webrtc", "websocket"],
    connection: "websocket",
    wsPort: 8088,
    loggerAnchor: ".log",
    logLevel: 4,
    cardsDeal: 6,
    maxScore: 30,
    direction: 1,
    voteForOwn: false,
    allowChangeMove: true,
    cardsCount: 84,
    scoreAllReg: 2,
    scoreAllStoryteller: 0,
    scoreNoneReg: 2,
    scoreNoneStoryteller: 0,
    scoreAdditionReg: 1,
    scoreAdditionStoryteller: 0,
    scoreGuessReg: 3,
    scoreGuessStoryteller: 3,
    botCount: 2,
    playerIsBot: false,
    idNameInStorage: "my-id",
    idNameLen: 6,
    maxClickToBan: 5,
    showAll: false,
    clickAll: false,
    seed: "",
    maxNameLen: 11
};
