export default {
    modes: ["net", "ai", "server", "hotseat"],
    mode: "net",
    connections: ["webrtc", "websocket"],
    connection: "websocket",
    wsPort : 8088,
    loggerAnchor: ".log",
    logLevel: 7,
    cardsDeal: 6,
    maxScore: 30,
    voteForOwn: false,
    allowChangeMove: false,
    cardsCount: 84,
    botCount: 2,
    playerIsBot: false,
    idNameInStorage: "my-id",
    idNameLen : 6,
    maxClickToBan: 5,
    showAll: false,
    clickAll: false,
    seed: "",
    dealAnim: 500,
    betweenRounds: 900,
    shuffleOutDelay: 150,
    shuffleInDelay: 150,
    shuffleWaitDelay: 200,
    shuffleSmallDelay: 10,
    shuffleTimes: 2,
    shuffleMaxCardsShow: 20,
    maxNameLen: 15
};
